### ISSUE TITLE
Log errors to the cli

### ISSUE THREAD

**Issue by caillou** [upfrontIO/livingdocs-design-manager#4]
When running an ``ldm publish`` that fails on the server side, all we get is the following message:

**ERR! Error: Bad Request**

**Comment by marcbachmann** [comment]
Fixed in 589a486c844e778599493180c0e82de395350e1f
![screen shot 2015-01-27 at 15 17 54](https://cloud.githubusercontent.com/assets/431376/5919830/b5468d26-a637-11e4-8fd9-66c1ffad005a.png)

I just log the whole error object. The server response is on the bottom as json.
